version: "3.11"

services:
  db_blog:
    image: postgres
    volumes:
      - ./data/db_blog:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - USE_LIVE_DB=false
    command: python blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_blog